repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2  # Use the appropriate version of ruff
    hooks:
      - id: ruff
        args: [--fix]  # Automatically fix linting issues
      - id: ruff
        name: ruff-check
        args: []  # Only check for linting issues without fixing
