name: Build and Lint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
      - preview
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run ruff format
        run: uv run ruff format .

      - name: Run ruff check
        run: uv run ruff check .
